### ISSUE TITLE
Can't compile: Cannot assign value of type '() -> Void' to type '(() -> Void)!' - swift 3

### ISSUE THREAD

**Issue by PatrickKaalund** [vikmeup/SCLAlertView-Swift#223] opened 2016-08-16 15:31 UTC
I get this error when trying to compile SCLAlertView in swift 3 - xcode 8 beta 6.

Anyone have an idea how to fix it?

../Pods/SCLAlertView/SCLAlertView/SCLAlertView.swift:409:22: 
Cannot assign value of type '() -> Void' to type '(() -> Void)!'
<img width="1179" alt="skaermbillede 2016-08-16 kl 17 29 08" src="https://cloud.githubusercontent.com/assets/9962378/17705011/2cc7b574-63d7-11e6-82e2-c849e77e438f.png">

Thank you

**Comment by udaymedic** [comment] 2016-09-05 03:16
Hello folks,

Did anyone found the fix for this problem. I am facing the exact build error in Xcode 8 beta 6 and swift 3.0

**Comment by udaymedic** [comment] 2016-09-05 03:23
Try chaging the method header of your addButton(_:action:) to:

public func addButton(_ title:String, action:@escaping ()->Void)->SCLButton {
The diagnostic messages from new betas are so confusing and inadequate as usual, but making your property simply non-Optional var action:()->Void = {} will give you a little more useful info.

**Comment by HowardTheDuck007** [comment] 2016-09-05 14:41
Same here, once changed as suggested by udaymedic, the compiler keeps showing a "Expression was too complex to be solved in reasonable time..." 

at line
colorAsUInt32 += UInt32(red * 255.0) << 16 + UInt32(green * 255.0) << 8 + UInt32(blue * 255.0)

and if you split it or even try to temporarily commenti it, the compiler shows a 
Command failed due to signal: Segmentation fault: 11

Does anyone succeed in porting this great library to Swift 3.0?

**Comment by vikmeup** [comment] 2016-09-05 23:35
@Patrick2990 try going into `swift3` branch. Let me know if that works

**Comment by HowardTheDuck007** [comment] 2016-09-06 18:56
Hi, I understand this may be a silly question due to my lack of experience with cocoapods but....how should I install swift 3 branch?
Uninstall pod and manually add the branch files or update through cocoapods? Thanks!

**Comment by Patrick2990** [comment] 2016-09-08 10:04
@vikmeup thank you very much. The issue is fixed in swift3 branch now!

**Comment by Patrick2990** [comment] 2016-09-20 19:17
@kressm add this to your pod file: 
pod 'SCLAlertView', :git => 'https://github.com/vikmeup/SCLAlertView-Swift.git', :branch => 'swift3'

**Closed** 2023-10-25 20:33 UTC
